### ISSUE TITLE
Unexpected lock of 4xx ms, dry run has been enabled

### ISSUE THREAD

**Issue by ArcticLobster** [UnknownX7/NoClippy#11]
I recently installed NoClippy and followed the installation set-ups. After casting a skill and trying to weave however, it automatically enables the 'dry run' setting and logs the error message: "Unexpected lock of 492 ms, dry run has been enabled."

Any idea what the cause could be?

**Comment by ArcticLobster** [comment]
I think it occurred because I was running both XIVAlexander and NoClippy at the same unintentionally. Unloading XIVAlexander solved the issue.

**Comment by UnknownX7** [comment]
Yep, this is a safety feature to prevent people from accidentally (or intentionally) using both.
