### ISSUE TITLE
Issues with Queue Threshold

### ISSUE THREAD

**Issue by BeetleLord** [UnknownX7/NoClippy#12]
Hello there, I would enjoy using the Queue Threshold option, but currently a few issues stop me from being able to do so.

1) Certain Machinist skills (Drill, Air Anchor, Chain Saw, Bioblaster, Flamethrower) are unaffected by the modified queue value and continue to behave normally. Other skills like Split/Slug/Clean Shot are all affected by the queueing change. I have not found this issue on any other classes, but I haven't tested them all.

2) While a skill is queued, it is impossible to use an oGCD. For example: if you queue a GCD skill with 2 seconds remaining until it will be activated, during those 2 seconds, you will be unable to use any oGCD skills. This makes it nearly unusable for longer queue durations, as it's quite easy to accidentally queue something then be locked out of oGCD usage.

3) As a potential enhancement, it would be useful to allow an inverted option which makes skills non-queueable for X duration after a GCD. This would make things cleaner for those who prefer large queue times but play classes with very different GCD durations.

**Comment by UnknownX7** [comment]
1. Currently, it only supports GCDs. oGCDs are always queued except when they are on a cooldown longer than 0.5s.
2. This is a feature of the game, just not as noticeable at 0.5s.
3. I have a similar unreleased feature, but this could be a good addition too.

I had plans to expand this feature recently and have some preliminary work done on it, but I'm unsure of its future in NoClippy. I will likely end up adding a more customizable version to [ReAction](https://github.com/UnknownX7/ReAction) instead and restricting NoClippy's scope to fixing latency related issues.

**Comment by BeetleLord** [comment]
1) All of the aforementioned skills are in fact GCDs. Flamethrower is a bit odd since it's channeled, but the rest are just ordinary GCD weaponskills. Maybe their skill IDs fall outside of whatever pattern or grouping of IDs you're catching to alter their behavior.

2) I understand that it's a feature of the game, but it makes large queue times borderline unusable in actual gameplay. I'm not sure whether it would be technically possible to do anything about this, but I brought it up in hopes that it could be altered somehow. Although I realize it goes beyond the original scope of the project.

I agree that the feature overall probably belongs in ReAction as opposed to NoClippy, especially if you begin adding more features and customizability to it.

**Comment by UnknownX7** [comment]
Ah, yeah I have a somewhat working change to allow requeuing so that will be in the more customizable version. I'll have to look at cooldown GCDs as well it seems, thanks for bringing it to my attention.

**Comment by UnknownX7** [comment]
[ReAction](https://github.com/UnknownX7/ReAction)'s replacement for this feature should fix these, please let me know if you encounter any new issues with it.
