### ISSUE TITLE
Predict Statuses

### ISSUE THREAD

**Issue by fbordwell** [UnknownX7/NoClippy#13]
Thank you for the excellent plugin. Could you please explain a bit further the effects of "predict statuses" and "predict mudras?" The description says it removes the effects of lag on these statuses, but it's not clear to me what effects of lag these suffer besides the standard animation lock that is addressed by this plugin.

**Comment by UnknownX7** [comment]
Higher latency can cause you to begin casting before a cast becomes instant, or make mudras feel unresponsive. Though, it's only normally a problem if you spike up to around 250+ randomly. You should only enable them if any of those statuses seem to not be applied before the next action.
