### ISSUE TITLE
Danger of setting the animation lock to constant value?

### ISSUE THREAD

**Issue by perks** [UnknownX7/NoClippy#16]
Is there a reason why  `Game.actionManager->animationLock` can't be set to a constant value like `0.5f` (from which i understand is the default 500ms additional animation lock) to simulate 0 ping? Afaik even with it at 500 (as long as you dont go under) you won't be able to triple weave anything.

**Comment by UnknownX7** [comment]
The usual lock is 600 ms, but nobody actually receives a response instantly even on 0 ms ping. Additionally, not all locks are the same length.
