### ISSUE TITLE
Queue Threshold at 2.5 has bug

### ISSUE THREAD

**Issue by Dyucrane** [UnknownX7/NoClippy#18]
I've noticed that queueing actions that are on CD that have <=10s left on the timer disables you from casting any other actions until the action in queue has been used. This is only for a queue threshold of 2.5. I fixed this by simply changing to a queue threshold of 2.4.

This plagued me for a while, for I thought it was because of another plugin's features. But I found out that it was because of NoClippy.

**Comment by UnknownX7** [comment]
This should no longer be an issue in [ReAction](https://github.com/UnknownX7/ReAction)'s replacement for this feature.
