### ISSUE TITLE
Bug with Predict Mudra

### ISSUE THREAD

**Issue by perks** [UnknownX7/NoClippy#2]
I know it is experimental, just wanted to make a note of a bug and see whether I can do anything on my end to collect more information for you.

Sometimes when this option is enabled, queuing up a single mudra action will cause the Mudra GCDs to "lock" for a  brief second  (perhaps smaller than second) and shows the 'Fuma' Ninjutsu briefly + decrementing the mudra charge , before "resetting" back to normal

**Comment by UnknownX7** [comment]
Can you record a video? Also, what is your ping, I'm curious if this is the same bug I was experiencing at extremely high ping where I would press 2 OGCD and everything would lock for a moment.

**Comment by perks** [comment]
Hi finally managed to get a clip of it happening, here it is:

https://imgur.com/a/VuHRMSA

at the time my ms was only 30 or 25 so I am not playing on an extreme ping situation

**Comment by UnknownX7** [comment]
I see the issue, the mudras are in the wrong state. I'm guessing that they can get stuck if they get used during certain events like dying. You can tell if it will happen by checking if they have a charge number / 0.5s recast. Using one fixes the state shortly after, without actually using it.

**Comment by UnknownX7** [comment]
Should hopefully be fixed in 2ba4fca44a5b40b28e9336e4ec8b1fd7da4d45d7
