### ISSUE TITLE
Crashing in PVP.

### ISSUE THREAD

**Issue by Zeemgeem** [UnknownX7/NoClippy#22]
Noclippy seems to be causing crashes consistently in PVP on the current testing build of Dalamud.

**Comment by Slightlyxz** [comment]
Generally seems like it's causing crashes randomly, died to Endsinger Ex raidwide friend and me crashed, after I uninstalled it my friend crashed again but I didn't.

**Comment by halcyonight** [comment]
Yup noclippy now sporadically crashes the game when I use a skill on the dalamud testing build. Happens often on MCH. None on BRD thus far.

**Comment by UnknownX7** [comment]
I'm so sorry, this was completely my fault. This has been fixed in v0.4.0.8.
