### ISSUE TITLE
Log File?

### ISSUE THREAD

**Issue by KrazyKC12** [UnknownX7/NoClippy#25]
I was wondering if the logs go to a file on my PC somewhere?  I'd like to review the logs after I get done practicing on a dummy but I don't necessarily want it in my in-game chat.

OR is there a way to make it have it's own window in the chat box?  Just trying to figure out how to use this program to its full potential.  Thanks in advance for the help.

**Comment by UnknownX7** [comment]
You can see it in-game by using `/xllog` or find the file at `%AppData%/XIVLauncher/dalamud.log`

**Comment by KrazyKC12** [comment]
Thanks
