### ISSUE TITLE
Changes with 6.15

### ISSUE THREAD

**Issue by leticiavalentini** [UnknownX7/NoClippy#27]
This is more a question than an issue, but with patch 6.15's changes in packet compression, is NoClippy still expected to work? I normally use XIVAlexander, but the maintainer may or may not be able to fix the breaking change introduced by the patch.

**Comment by UnknownX7** [comment]
Yes, NoClippy works by hooking the function that processes the packet and reading/writing the animation lock directly rather than using opcodes. Currently, none of the Dalamud beta testers have reported any issues.

**Comment by VXLSS** [comment]
I use both xivalex and noclippy usually, since xivalex was not expected to work i fully uninstalled it and restarted my game with just no clippy and default settings but it is not working for me. Friends facing the same issue

**Comment by UnknownX7** [comment]
If you use both at the same time it will automatically enable "Dry Run", the following image is of the default settings for reducing the animation lock.

![image](https://user-images.githubusercontent.com/12263784/172504742-8a6fec01-0263-4585-a420-7bf0fd852345.png)

**Comment by VXLSS** [comment]
It is perfectly working now, thank you.
