### ISSUE TITLE
Extreme lag input and random disconnect icon.

### ISSUE THREAD

**Issue by TheBlue3000** [UnknownX7/NoClippy#28]
Greetings. I'm having this issue with NoClippy since... basically I started using it. I run NoPing as a VPN. After a while of playing, it seems like NoClippy stops working and I get a massive lag input that makes combos to not go off or skills to be used. I logged the before and after. I usually restart the whole thing and the issue fixes itself, but after a while it goes back to it. I don't know what's causing it.
![Issue](https://user-images.githubusercontent.com/81864554/173213524-b4b47a00-3aa4-4877-a3a3-4306825df4fc.png)

I run the game on Win10 64bits with the DX11 client.

**Comment by UnknownX7** [comment]
This is likely a network / network equipment issue as NoClippy doesn't actually affect ping. I've had a similar issue in other games that have been caused by an overheating router.
