### ISSUE TITLE
NoClippy not working

### ISSUE THREAD

**Issue by Rossier** [UnknownX7/NoClippy#30]
Ever since the 6.18 hotfix my noclippy hasnt been able to work. I have tried uninstalling the plugin and reinstalling it and disabling it and removing it altogether but it still wouldnt work. I don't know if there is something I am missing?

**Comment by UnknownX7** [comment]
What settings are you using?

**Comment by Rossier** [comment]
The default ones that come with installing it

**Comment by UnknownX7** [comment]
Enable logging and output to chat log (or just copy them from the Dalamud log file or /xllog ingame), and post it here.

**Comment by Rossier** [comment]
--------------------------------
20:17:46.683 | INF [IME] Enabled!
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin Triad Buddy
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin NoClippy
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin ezMiniCactpot
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin Mouseover Action Plugin
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin Pixel Perfect
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin AntiAfkKick-Dalamud
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin Fancy Loading Screens
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin ezWondrousTails
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin PingPlugin
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin Penny Pincher
--------------------------------
20:17:46.749 | INF [PLUGINM] Loading plugin Globetrotter
--------------------------------
20:17:46.855 | INF [LOCALPLUGIN] Loading PixelPerfect.dll
--------------------------------
20:17:46.855 | INF [LOCALPLUGIN] Loading PennyPincher.dll
--------------------------------
20:17:46.857 | INF [LOCALPLUGIN] Loading EnemyListDebuffs.dll
--------------------------------
20:17:46.861 | INF [LOCALPLUGIN] Loading MOAction.dll
--------------------------------
20:17:46.877 | INF [LOCALPLUGIN] Loading NoClippy.dll
--------------------------------
20:17:46.879 | INF [LOCALPLUGIN] Finished loading PixelPerfect.dll
--------------------------------
20:17:46.889 | INF [LOCALPLUGIN] Loading PingPlugin.dll
--------------------------------
20:17:46.921 | INF [PingPlugin] Loading lang data from PingPlugin.Lang.lang_en.json
--------------------------------
20:17:46.936 | INF [LOCALPLUGIN] Finished loading PingPlugin.dll
--------------------------------
20:17:46.941 | INF [LOCALPLUGIN] Loading Glamaholic.dll
--------------------------------
20:17:46.967 | INF [LOCALPLUGIN] Loading TriadBuddy.dll
--------------------------------
20:17:46.978 | INF [LOCALPLUGIN] Finished loading PennyPincher.dll
--------------------------------
20:17:47.023 | INF [PLUGINR] Successfully fetched repo: https://ffxiv.akurosia.de/ffxiv_custom_repo.json
--------------------------------
20:17:47.024 | INF [PLUGINM] PluginMasters reloaded, now refiltering...
--------------------------------
20:17:47.025 | INF [LOCALPLUGIN] Finished loading TriadBuddy.dll
--------------------------------
20:17:47.071 | INF [LOCALPLUGIN] Loading MiniCactpotSolver.dll
--------------------------------
20:17:47.075 | INF [EnemyListDebuffs] 7FF66428C350
--------------------------------
20:17:47.076 | INF [AntiAfkKick-Dalamud] RaptureAtkModule: 000001A3818E8DA0
--------------------------------
20:17:47.076 | INF [LOCALPLUGIN] Finished loading AntiAfkKick-Dalamud.dll
--------------------------------
20:17:47.077 | INF [LOCALPLUGIN] Finished loading Dalamud.LoadingImage.dll
--------------------------------
20:17:47.077 | INF [LOCALPLUGIN] Finished loading Globetrotter.dll
--------------------------------
20:17:47.078 | INF [LOCALPLUGIN] Finished loading EnemyListDebuffs.dll
--------------------------------
20:17:47.094 | INF [LOCALPLUGIN] Finished loading MiniCactpotSolver.dll
--------------------------------
20:17:47.105 | INF [NoClippy] Loaded module: NoClippy.Modules.AnimationLock
--------------------------------
20:17:47.105 | INF [NoClippy] Loaded module: NoClippy.Modules.Logging
--------------------------------
20:17:47.109 | INF [LOCALPLUGIN] Finished loading NoClippy.dll
--------------------------------
20:17:47.131 | INF [LOCALPLUGIN] Loading WondrousTailsSolver.dll
--------------------------------
20:17:47.245 | INF [AntiAfkKick-Dalamud] Obtained base address: 000001A3818CBB48
--------------------------------
20:17:47.265 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Axis18, 18pt, skew=0, weight=0)" has been requested.
--------------------------------
20:17:47.854 | INF [MOAction] ===== M O A C T I O N =====
--------------------------------
20:17:47.855 | INF [MOAction] SetUiMouseoverEntityId address "140696220472976"
--------------------------------
20:17:47.913 | INF [LOCALPLUGIN] Finished loading SonarPlugin.dll
--------------------------------
20:17:48.067 | INF [LOCALPLUGIN] Finished loading MOAction.dll
--------------------------------
20:17:48.400 | INF [TriadBuddy] Loaded game data for cards:357, npcs:110
--------------------------------
20:17:48.650 | INF [LOCALPLUGIN] Finished loading Glamaholic.dll
--------------------------------
20:17:48.704 | INF [SonarPlugin] Initializing Sonar
--------------------------------
20:17:48.704 | INF [SonarPlugin] Lumina Data initialized
--------------------------------
20:17:48.704 | INF [SonarPlugin] PlayerTracker initialized
--------------------------------
20:17:48.704 | INF [SonarPlugin] MobTracker Initialized
--------------------------------
20:17:48.704 | INF [SonarPlugin] FateTracker Initialized
--------------------------------
20:17:49.687 | INF [SonarPlugin] Sonar is ready
--------------------------------
20:17:49.690 | INF [SonarPlugin] Connected to Sonar
--------------------------------
20:17:50.413 | INF [LOCALPLUGIN] Finished loading WondrousTailsSolver.dll
--------------------------------
20:18:32.859 | INF [Dalamud.LoadingImage] LoadIcon: 0 detected for r:1 with toLoadingTerri:-1
--------------------------------
20:18:32.859 | INF [Dalamud.LoadingImage] toLoadingImage not set!
--------------------------------
20:18:35.548 | INF [PLUGINM] Starting plugin update
--------------------------------
20:18:35.549 | INF [PLUGINM] Plugin update OK.
--------------------------------
20:19:01.646 | INF [Dalamud.LoadingImage] toLoadingTerri: 641
--------------------------------
20:19:01.646 | INF [Dalamud.LoadingImage] LoadIcon: 122025 detected for r:628 with toLoadingTerri:641
--------------------------------
20:19:01.647 | INF [Dalamud.LoadingImage] Replacing icon for territory 628
--------------------------------
20:19:01.656 | INF [Dalamud.LoadingImage] unitbase: 1A40A212350 visible: True
--------------------------------
20:19:01.656 | INF [Dalamud.LoadingImage] unishort: 1A40A212660 visible: False
--------------------------------
20:19:01.656 | INF [Dalamud.LoadingImage] Swapped!
{ } [ Send ]

**Comment by UnknownX7** [comment]
Enable these two settings
![image](https://user-images.githubusercontent.com/12263784/180842389-59e0636e-e4f9-472c-af3f-ba9e8d32f6bd.png)
and then use some skills on a mob and copy these lines from the chat and send them here.
![image](https://user-images.githubusercontent.com/12263784/131718566-06352228-a61d-4e8a-a546-b9347318861b.png)

**Comment by Rossier** [comment]
![image](https://user-images.githubusercontent.com/81907477/180851774-97959dcb-4588-47eb-a79e-4cdb94b7f90a.png)

**Comment by UnknownX7** [comment]
Disable dry mode, it likely enabled due to XIVAlexander running at the same time.

**Comment by Rossier** [comment]
That works! Thank you so much!
