### ISSUE TITLE
Plugin disabling itself when it didn't before

### ISSUE THREAD

**Issue by jmrs2603** [UnknownX7/NoClippy#35]
I used NoClippy along with XIVAlexander and ACT when it started activating its dry run out of nowhere mid-session and now won't stop switching back even though both of these separate programs have been disabled. This issue has only started happening today (08/31/22).

**Comment by jmrs2603** [comment]
Forgot to mention that this only happens when I weave something, it says there's been an unexpected lock of around 500ms and enables dry run.

**Comment by UnknownX7** [comment]
NoClippy does this when it detects that something else is already reducing the animation lock.

**Comment by jmrs2603** [comment]
I'm not aware of anything else reducing the animation lock though.

**Comment by UnknownX7** [comment]
Are you sure XIVAlexander is disabled? NoClippy is specifically detecting that the packet has an animation lock value that the server wouldn't send. Try to close Alex and see if NoClippy is still detecting it.

**Comment by jmrs2603** [comment]
I am absolutely sure that Alex is disabled, I uninstalled it to try and troubleshoot.

**Comment by UnknownX7** [comment]
Please send me `%AppData%\XIVLauncher\dalamud.log` as well as this,
> Enable these two settings
![image](https://user-images.githubusercontent.com/12263784/180842389-59e0636e-e4f9-472c-af3f-ba9e8d32f6bd.png)
and then use some skills on a mob and copy these lines from the chat and send them here. ![image](https://user-images.githubusercontent.com/12263784/131718566-06352228-a61d-4e8a-a546-b9347318861b.png)
