### ISSUE TITLE
Change chat output log channel

### ISSUE THREAD

**Issue by rechington** [UnknownX7/NoClippy#38]
It seems after an update the chat output channel has been set to echo instead of what you have set globally in Dalamud. Would it be possible to let the user set the output channel? 

The reason is that echo is such a messy channel and other plugins don't work with it so nicely. Thanks!

**Comment by Uragawa** [comment]
I was surprised to look at the last commit and see that this was apparently an intended change. I redirect my plugin output to the unused ls8 channel and have it set to display in a different colour, and now the log displays in unremarkable grey. NoClippy's messages whenever you delay or clip a GCD are such an important feature for folks trying to improve their gameplay that I recommend the plugin even to people who don't need its main function.
