### ISSUE TITLE
Mudra Animation Lock

### ISSUE THREAD

**Issue by Ereaseth** [UnknownX7/NoClippy#40]
With predict Mudras off, trying to input ninjutsu results in hangups. While using Kassautsu this issue is not present. Issue persists when using predecit mudras (While on Kassatsu inputs are okay but outside of Kassatsu its off)

**Comment by UnknownX7** [comment]
Is this the issue? Its not NoClippy if so.
https://forum.square-enix.com/ffxiv/threads/476427-First-Mudra-Recast-seems-to-be-off

**Comment by Patrickmanx** [comment]
Seems to be an issue with Ff14 itself, the first mudra is off regardless of ping. Ive tested in a 140 ping enviroment and a 120 ping enviroment. As Op described its doesnt happen under kassatsu.

**Comment by UnknownX7** [comment]
I've gone ahead and added a temporary fix for the issue for the time being. There is no setting to enable, just by having NoClippy installed the issue will no longer be present.
