### ISSUE TITLE
Unexpected lock but XivAlexander not installed

### ISSUE THREAD

**Issue by JTT1991** [UnknownX7/NoClippy#43]
Hello,

I have begun getting this issue recently:

[NoClippy] Unexpected lock of 297 ms, temporary dry run has been enabled. Please disable any other programs or plugins that may be affecting the animation lock.

I searched online and found that this happens when XivAlexander is running. However I do not have it installed. Would anyone know if there's a way to check what is causing this conflict? Thank you!

**Comment by UnknownX7** [comment]
See [this](https://github.com/UnknownX7/NoClippy/issues/35#issuecomment-1233649446) issue for a possible solution.
