### ISSUE TITLE
Doesn't work with Exitlag

### ISSUE THREAD

**Issue by Danteezeezzz** [UnknownX7/NoClippy#44]
Hello! Whenever Exitlag is launched I'm getting this message.

![image](https://user-images.githubusercontent.com/123560185/214570883-7d292712-526f-4cff-a599-3ebef90332b7.png)

Is there any way to make them work together? 
Hope there's a way to fix this. Thank you!

**Comment by UnknownX7** [comment]
Exitlag is breaking your routing to GitHub. It may resolve on its own, but this is only required to install or update NoClippy so you can also temporarily disable it and then enable it afterwards.
