### ISSUE TITLE
Sometimes freezing when spamming provoke

### ISSUE THREAD

**Issue by amirullahizzan** [UnknownX7/NoClippy#45]

**Comment by UnknownX7** [comment]
Does this still occur? Is it occurring with only NoClippy and does it occur without any plugins?

**Comment by amirullahizzan** [comment]
I didn't use any other plugins at that time. The freeze was long compared to normal stutters (1-2 secs) so I can tell it wasn't a regular freeze or GPU issue and only happened when using Provoke. 

I tried Noclippy again now, and I think it's gone. I'll post if I find anything.
