### ISSUE TITLE
Download failed.

### ISSUE THREAD

**Issue by Jerichoooo** [UnknownX7/NoClippy#48]
![image](https://github.com/UnknownX7/NoClippy/assets/81920854/f1b1d1d8-d1ad-4e33-a5ff-bb2ee90382ac)

**Comment by Jerichoooo** [comment]
![image](https://github.com/UnknownX7/NoClippy/assets/81920854/6c4381f0-4e2a-4f32-8711-7074ce2b29c2)

**Comment by juliamlim** [comment]
I'm getting this issue too, how were you able to resolve it?
