### ISSUE TITLE
Crashes Since Recent Updates

### ISSUE THREAD

**Issue by The-Posh-Panda** [UnknownX7/NoClippy#55]
There seems to be random crashes associated with ReAction and NoClippy that do not occur when the plugins are disabled.

[dalamud_appcrash_20240613_132501_958_13584.log](https://github.com/user-attachments/files/15827199/dalamud_appcrash_20240613_132501_958_13584.log)
[dalamud_appcrash_20240612_162436_701_16208.log](https://github.com/user-attachments/files/15827200/dalamud_appcrash_20240612_162436_701_16208.log)
[dalamud_appcrash_20240613_113253_184_13176.log](https://github.com/user-attachments/files/15827201/dalamud_appcrash_20240613_113253_184_13176.log)

**Comment by The-Posh-Panda** [comment]
I have confirmed that without the experimental repository that houses noclippy and reaction, that the crashes don't happen. So, it might not be the specific plugin, but the repo as a whole causing the issue.

**Comment by UnknownX7** [comment]
Please let me know if this is still occurring post Dawntrail.

**Comment by The-Posh-Panda** [comment]
I won't be able to confirm because of Dawntrail, but I believe these crashes were not addon caused, but caused by a faulty cpu (L1/L2 caches).
