### ISSUE TITLE
Simulating 75ms like XIVAlexander

### ISSUE THREAD

**Issue by FloppyAl** [UnknownX7/NoClippy#7]
Hello,

I recently switched off XIVal to your tool but noticing that because I play on very high ping I sometimes still clip. 

I'm having trouble understanding the queue threshold and would like the same settings that XIValexander uses to simulate a flat 75ms. 
What would I set the queue threshold to? Thanks in advance for the great plugin!

**Comment by UnknownX7** [comment]
Can you enable these settings and show what NoClippy is reporting when you clip?
![image](https://user-images.githubusercontent.com/12263784/147363602-8e21aff3-2ef2-49eb-8eea-e998503115d9.png)

As for the queue threshold, it changes when the game allows queuing the next GCD while the GCD is still rolling. By default the game allows it at 0.5s left on the GCD, but that setting will let you change it. It doesn't help with ping so it can be safely ignored (Make sure to reset it to 0.5 or untick the box if you don't need it).
