### ISSUE TITLE
Game Exits when I step away

### ISSUE THREAD

**Issue by Rekuja** [UnknownX7/NoClippy#9]
Hey,

I've noticed sometimes when I step away from my PC (get the door, phone call, etc) not even 5 mins have passed and the game will exit. This never used to happen before I got XIV Launcher and I'm definitely not hitting the AFK timer. 

I asked on XIV Launcher discord and they couldn't see any issues, so I was wondering if it's the plugin NoClippy?

**Comment by UnknownX7** [comment]
Do you use any other feature besides animation lock compensation? While I haven't heard of anyone crashing, I'd first try to turn off everything but that. Otherwise, the only way to know for sure would be to just run the game with XIVLauncher and disable NoClippy. If it still crashes then it would have to be Dalamud.

**Comment by Rekuja** [comment]
> Do you use any other feature besides animation lock compensation? While I haven't heard of anyone crashing, I'd first try to turn off everything but that. Otherwise, the only way to know for sure would be to just run the game with XIVLauncher and disable NoClippy. If it still crashes then it would have to be Dalamud.
> 
> Edit: Just saw you posted logs that say "Game has exited.", is there any chance a third party program is closing the game? Logs for a CTD will be abrupt and wont have that message, which suggests the game is actually being closed by something.

I just tried without XIV Launcher, had a quick shower and came back, the game was at the main menu instead of being fully closed. 

I don't use any additional features, purely just xivlauncher + noclippy with the default setting. 

I will try with xivlauncher and i'll disable noclippy, see if i can replicate the issue.

**Comment by Rekuja** [comment]
so I reinstalled xivlauncher and it's not exiting the game anymore.

however.. when i try adding noclippy via https://raw.githubusercontent.com/UnknownX7/DalamudPluginRepo/master/pluginmaster.json

i click the +, apply, save and close, when i type in /xlplugins and go to the installed plugins section, noclippy is not there.. i didn't have this issue before, I followed the instructions same as last time.

**Comment by UnknownX7** [comment]
It should be under Available Plugins, if not then its still installed.
